version: "3"
services:
  web:
    build: ./images/web
    image: web
    container_name: gof_web
    ports: 
      - "80:80"
    volumes:
      - ./code:/var/www/site
  db:
    image: percona
    container_name: gof_db
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf