version: "3"
services:
  nginx:
    build: images/nginx/
    image: jameslyon42/nginx
    container_name: gof_nginx
    ports: 
      - "80:80"
    volumes:
      - ./code:/var/www/public
    environment:
      - FPMIP=172.18.18.10:9000
    networks:
      gof:
        ipv4_address: 172.18.18.9

  php:
    build: images/php/
    image: jameslyon42/php
    container_name: gof_php
    ports:
      - "9000:9000"
    volumes:
      - ./code:/var/www/public
    networks:
      gof:
        ipv4_address: 172.18.18.10

  db:
    build: images/db/
    image: jameslyon42/gof_db
    command: --port=5123
    container_name: gof_db
    ports:
      - "5123:5123"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
    networks:
      gof:
        ipv4_address: 172.18.18.11

networks:
  gof:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
